networks:
  go-redis:
    driver: bridge

services:
  mongo:
    container_name: go-redis_mongo
    image: mongo:5.0
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    networks:
      - go-redis
    ports:
      - ${MONGO_PORT}:27017

  redis:
    container_name: go-redis_redis
    image: redis:7.2.3
    restart: always
    env_file:
      - .env
    networks:
      - go-redis
    ports:
      - ${REDIS_PORT}:6379